#!/bin/sh
# Pre commit for python 
/usr/bin/env python3 -m pytest
if [ $? -ne 0 ]
then
	exit 1
fi
/usr/bin/env python3 -m pylint $(git diff --name-only --cached '*.py')
if [ $? -eq 8 ]
then
	exit 0
fi


