name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11" ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      id: pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: checking
      if: ${{ steps.pylint.outcome == failure }}
      uses: dudisamarel/reset-head@v1
      with:
    # The name of the branch to reset.
        branch-name: main
    - name: Making unitesting
      uses: xoviat/actions-pytest@0.1-alpha2
  
